POST localhost:8080/auth/public/login
Content-Type: application/json

{
  "username": "uz_card_shoh",
  "password": "00"
}
###
POST localhost:8080/auth/public/login
Content-Type: application/json

{
  "username": "AnorBank",
  "password": "00"
}