POST localhost:8080/client/bank/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg1Nzc1MjMsImV4cCI6MTY1ODU4MTEyMywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGFiN2Q4MjJhZTNlMTAxODIyYWU1YzMzMTAwMDIiLCJyb2xlIjoiUk9MRV9CQU5LIiwicGFzc3dvcmQiOiJiNGIxNDdiYzUyMjgyODczMWYxYTAxNmJmYTcyYzA3MyIsInVzZXJuYW1lIjoiQW5vckJhbmsiLCJzdGF0dXMiOiJBQ1RJVkUifQ.5TBgJNKRhtrL4u7ejSKaxX4iQFDsUzCBOsNnkgsCLbg

{
  "name": "Omonxonov",
  "surname": "Saidkarim",
  "middleName": "suxrov",
  "status": "ACTIVE",
  "passportNumber": "AA",
  "passportSeria": "12344610",
  "phone": "4679"
}

###
PUT localhost:8080/profile/adm/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgyNTQzNjgsImV4cCI6MTY1ODI1Nzk2OCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiZmY4MDgwODE4MjE2NjE3MjAxODIxNjYyMGMzOTAwMDEifQ.66s5WN4izTSaSjqdsGijjkQ-LF0bDuixR-Xb4z4UOCw

{
  "id": "4028818382171710018217178fac0000",
  "name": "jahon",
  "surname": "holmurodov",
  "password": "00"
}

###
GET localhost:8080/client/adm/pagination
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgzODc4MzEsImV4cCI6MTY1ODM5MTQzMSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiZmY4MDgwODE4MjE2NjE3MjAxODIxNjYyMGMzOTAwMDEiLCJyb2xlIjoiUk9MRV9BRE1JTiIsInBhc3N3b3JkIjoiYjRiMTQ3YmM1MjI4Mjg3MzFmMWEwMTZiZmE3MmMwNzMiLCJ1c2VybmFtZSI6ImthcmlteG9uIiwic3RhdHVzIjoiQUNUSVZFIn0.1vuhPq_w8Kqc-Huq8YJNqlAJW0xmWzlr_jYlHfqfbTI

{
  "status": "ACTIVE"
}