POST localhost:8080/company/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg1NzcwMjksImV4cCI6MTY1ODU4MDYyOSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGFiN2Q4MjJhZTNlMTAxODIyYWU0MWQ2YjAwMDAiLCJyb2xlIjoiUk9MRV9BRE1JTiIsInBhc3N3b3JkIjoiYjRiMTQ3YmM1MjI4Mjg3MzFmMWEwMTZiZmE3MmMwNzMiLCJ1c2VybmFtZSI6ImthcmlteG9uIiwic3RhdHVzIjoiQUNUSVZFIn0.klRfMgW0IC-fuCa-L4k1T3qshxAyEJi8ggGmCb23Md4

{
  "name": "AnorBank",
  "address": "chilanzar",
  "contact": "0987654321",
  "role": "ROLE_UZCARD",
  "status": "ACTIVE",
  "username": "AnorBank",
  "password": "00"
}

###
PUT localhost:8080/company/adm/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgyNTQzNjgsImV4cCI6MTY1ODI1Nzk2OCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiZmY4MDgwODE4MjE2NjE3MjAxODIxNjYyMGMzOTAwMDEifQ.66s5WN4izTSaSjqdsGijjkQ-LF0bDuixR-Xb4z4UOCw

{
  "id": "402881838217a49d018217ad0b3f0001",
  "name": "ANORBANK",
  "address": "chilonzor",
  "contact": "1234567890",
  "role": "ROLE_BANK",
  "status": "ACTIVE",
  "username": "anor_bank",
  "password": "00"
}
###
GET localhost:8080/company/adm/pagination
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgyNTQzNjgsImV4cCI6MTY1ODI1Nzk2OCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiZmY4MDgwODE4MjE2NjE3MjAxODIxNjYyMGMzOTAwMDEifQ.66s5WN4izTSaSjqdsGijjkQ-LF0bDuixR-Xb4z4UOCw


