POST localhost:8080/transfer/all/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg0MjE5MjIsImV4cCI6MTY1ODQyNTUyMiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyODgxODM4MjFhNzYzNDAxODIxYTc3M2M3OTAwMDAiLCJyb2xlIjoiUk9MRV9CQU5LIiwicGFzc3dvcmQiOiJiNGIxNDdiYzUyMjgyODczMWYxYTAxNmJmYTcyYzA3MyIsInVzZXJuYW1lIjoiQU5PUkJBTksiLCJzdGF0dXMiOiJBQ1RJVkUifQ.5b1bTSogGs4XbnvvbYGsKjCTVstR76IAeBo3vUOamuM

{

  "fromCard" : "8600550510021455",
  "toCard" : "8600267403345780",
  "amount" : 15000,
  "companyId" : "40288183821a763401821a773c790000"
}


###
PUT localhost:8080/profile/adm/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgyNTQzNjgsImV4cCI6MTY1ODI1Nzk2OCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiZmY4MDgwODE4MjE2NjE3MjAxODIxNjYyMGMzOTAwMDEifQ.66s5WN4izTSaSjqdsGijjkQ-LF0bDuixR-Xb4z4UOCw

{
  "id": "4028818382171710018217178fac0000",
  "name": "jahon",
  "surname": "holmurodov",
  "password": "00"
}

###
GET localhost:8080/client/adm/pagination
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgzODc4MzEsImV4cCI6MTY1ODM5MTQzMSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiZmY4MDgwODE4MjE2NjE3MjAxODIxNjYyMGMzOTAwMDEiLCJyb2xlIjoiUk9MRV9BRE1JTiIsInBhc3N3b3JkIjoiYjRiMTQ3YmM1MjI4Mjg3MzFmMWEwMTZiZmE3MmMwNzMiLCJ1c2VybmFtZSI6ImthcmlteG9uIiwic3RhdHVzIjoiQUNUSVZFIn0.1vuhPq_w8Kqc-Huq8YJNqlAJW0xmWzlr_jYlHfqfbTI

{
  "status": "ACTIVE"
}