GET localhost:8080/transaction/bankAndPayment/pagination/4028ab7d822aebb801822af059010003
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg1ODA4ODMsImV4cCI6MTY1ODc5Njg4MywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGFiN2Q4MjJhZTNlMTAxODIyYWU1YzMzMTAwMDIiLCJyb2xlIjoiUk9MRV9CQU5LIiwicGFzc3dvcmQiOiJiNGIxNDdiYzUyMjgyODczMWYxYTAxNmJmYTcyYzA3MyIsInVzZXJuYW1lIjoiQW5vckJhbmsiLCJzdGF0dXMiOiJBQ1RJVkUifQ.vfQEkdVVnxMUjmKOspJrN2C972fjhderXozz0cE54Gw

###
GET localhost:8080/transaction/bankAndPayment/byProfileId/4028ab7d822aebb801822aeee1800002
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg1NTk0MzUsImV4cCI6MTY1ODU2MzAzNSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyODgxODM4MjFhNzYzNDAxODIxYTc3M2M3OTAwMDAiLCJyb2xlIjoiUk9MRV9CQU5LIiwicGFzc3dvcmQiOiJiNGIxNDdiYzUyMjgyODczMWYxYTAxNmJmYTcyYzA3MyIsInVzZXJuYW1lIjoiQU5PUkJBTksiLCJzdGF0dXMiOiJBQ1RJVkUifQ.W7ovR10VKmM3JCa1nMbHUO-cW1EiiRZc1OwCzighMec
###
GET localhost:8080/transaction/bankAndPayment/debit/8600267403345780
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg1NzM2NjYsImV4cCI6MTY1ODU3NzI2NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyODgxODM4MjFhNzYzNDAxODIxYTc3M2M3OTAwMDAiLCJyb2xlIjoiUk9MRV9CQU5LIiwicGFzc3dvcmQiOiJiNGIxNDdiYzUyMjgyODczMWYxYTAxNmJmYTcyYzA3MyIsInVzZXJuYW1lIjoiQU5PUkJBTksiLCJzdGF0dXMiOiJBQ1RJVkUifQ.0TyCP180Iwob6eqanM4q3RDenCufDrpeNkG95Jn910I



###
GET localhost:8080/transaction/bankAndPayment/month/40288189822ed54101822ed6d1700000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg2NDg0OTMsImV4cCI6MTY1ODg2NDQ5MywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGFiN2Q4MjJhZTNlMTAxODIyYWU1YzMzMTAwMDIiLCJyb2xlIjoiUk9MRV9CQU5LIiwicGFzc3dvcmQiOiJiNGIxNDdiYzUyMjgyODczMWYxYTAxNmJmYTcyYzA3MyIsInVzZXJuYW1lIjoiQW5vckJhbmsiLCJzdGF0dXMiOiJBQ1RJVkUifQ.hquum7cOLAhvsufMxBClc5lBA_1hJFNowZl84S6xW6c


